// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: backportRequest.proto

package backportRequest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackportRequestServiceClient is the client API for BackportRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackportRequestServiceClient interface {
	RunBackport(ctx context.Context, in *BackportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type backportRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackportRequestServiceClient(cc grpc.ClientConnInterface) BackportRequestServiceClient {
	return &backportRequestServiceClient{cc}
}

func (c *backportRequestServiceClient) RunBackport(ctx context.Context, in *BackportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/BackportRequestService/RunBackport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackportRequestServiceServer is the server API for BackportRequestService service.
// All implementations must embed UnimplementedBackportRequestServiceServer
// for forward compatibility
type BackportRequestServiceServer interface {
	RunBackport(context.Context, *BackportRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBackportRequestServiceServer()
}

// UnimplementedBackportRequestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBackportRequestServiceServer struct {
}

func (UnimplementedBackportRequestServiceServer) RunBackport(context.Context, *BackportRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunBackport not implemented")
}
func (UnimplementedBackportRequestServiceServer) mustEmbedUnimplementedBackportRequestServiceServer() {
}

// UnsafeBackportRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackportRequestServiceServer will
// result in compilation errors.
type UnsafeBackportRequestServiceServer interface {
	mustEmbedUnimplementedBackportRequestServiceServer()
}

func RegisterBackportRequestServiceServer(s grpc.ServiceRegistrar, srv BackportRequestServiceServer) {
	s.RegisterService(&BackportRequestService_ServiceDesc, srv)
}

func _BackportRequestService_RunBackport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackportRequestServiceServer).RunBackport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackportRequestService/RunBackport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackportRequestServiceServer).RunBackport(ctx, req.(*BackportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackportRequestService_ServiceDesc is the grpc.ServiceDesc for BackportRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackportRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BackportRequestService",
	HandlerType: (*BackportRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBackport",
			Handler:    _BackportRequestService_RunBackport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backportRequest.proto",
}
